---
language: python

python:
    - '3.9'

env:
    matrix:
        - DJANGO_VERSION=3.2.6
        - DJANGO_SETTINGS_MODULE='stackit.settings'
    global:
        secure: >
            nR3XKFxOmGOsrlOYfUV0fpBpnCWVrxyuNfnoc1+5QTJRfiNLKEh/klByFsbXu/ppS8VehGuxiYcnMI
            3W8DcKqKUHrxATMUKLff1Ze7uvo0giajAmLbFyLCgNR3L545kY57kGo+NdIDL14ke+g7S06pfYbRMm
            yfueEtsydk36E5+t4jOkuBNDlrzPVPcrw6I4C96dvYUqDZSrc5fjpHKaJyEzMR+Cfee/hKtLZyvAEZ
            s9nN6m+DeaTClCpO3DE4LFL+DlKxkbh7A/n8p6b6BwclipdeXENTq6sJR0i3IwvlhN0tkZYcR8OgAm
            zOplMA/Erywqw+aEJZl9ymQw3zQI7agxBQbwg8M8ZAu9yGjoCWCxHPk1s/zR8Ysp2RYSJDPDA7+dil
            eGmcFiqWG/P5W99DyZjWzmC8ZyBa710Xnj1rqZZSNyEYmC4xmJyZq7gfLe6mWEISZNYXWv32ac9BXL
            lgfz+XXjKq8lmLm7LEidjQZk/nR2YQ9o5acFcSWnu4uxOC2WCyTCu53NjmFyMCOtoFkm9BroC3Kwt2
            lRjabc3rWLSU7Yfrrmg15KWFPelHTDOH6Hz0fOTx/dHbK2NjfFMcluYaGOO+rbYl7OIQOCZNJldpJ1
            X8S3z00jExTN5d7V8RUR369MesovY++8RmvA8us/nGp2dVCwKVr2MbDm5dM=

install:
    - pip install -r requirements.txt

before_script:
    - curl -sL https://firebase.tools | bash

script:
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
    - coverage run --source=home manage.py test home

after_success:
    - coveralls

deploy:
    provider: firebase
    project: stackit-a89ad
    token:
        secure: >
            P+0krxZwDDJGsl/w383w7uoGGEwe3GJXu1uOpWa+ejK7JODD8hhcFIZGFjlCMzGqGjN+
            /V8xmd+zXVbpnJwv6IrhXzn1b0gt9m2+RMjzFKvRJKCBWGC4wxm957bYxkjJf9PfAr5p
            N0Ontf4YkS36luQEkyQNlQUDACztiUwo6b6SJa0H2+Du+FBkidczgTL+qhTiD+es/aiM
            UzV2ROob3sXTiu6vYc7aMeFiYH7H4XGA4JsRrYjzz8Ynd7Z3nwLHByDcRoyn1mc88MSx
            NA+J7iOFparJvEvLMFZDmdn0APRkxW0OfTaHO0o4dRh3MIqaf6fsxb5bwFfhQo/vCZGP
            f8GOwCi+fnhklBz1X8mWVxaf+ObxcrJOae/sBj0SOh+wI2ArjOSZmFlW/UKWSJ7ao1RH
            5cYurwm1vlaCaZTHTEFcqoSExItuFs7HO2dEZYYzW7F5DPrQm57G1N3aeEUrq7GTRYTP
            gkPYWl8EHmtWBjzvyE1RQDq4Z0quaJzMl5zMW5rP9JYAVwCua77qhk6nmrKEn7DS3eWK
            7Fo9tlzjis5qGoabxrvTQ9ROgEeBlL0cnY8vQAN7IrcH9sgdXrOfZNjyMt2z0ebRlVQa
            1Lu4BWKUethFb/AraVpMSkHDfTSGiPHbJgmaiQtwLQKACG8BZXcoYfU+x2D7TsY+gBhNMIA=

message: >
    "this is an automatic deployment by travis - CI
    as a result of pushing to master"

before_deploy: echo 'ready?'

after_deploy:
    - export DJANGO_SETTINGS_MODULE=stackit.settings
    - python manage.py test home --noinput --settings=stackit.settings
    - python manage.py makemigrations --settings=stackit.settings
    - python manage.py migrate --settings=stackit.settings
