---
runtime: python39  # or another supported version

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  DJANGO_SETTINGS_MODULE: "stackit.settings"

handlers:
  # Matches requests to /images/... to files in static/images/...
  - url: /images
    static_dir: static/images
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

error_handlers:
  - error_code: over_quota

automatic_scaling:
  target_cpu_utilization: 0.75
  max_instances: 1
  max_pending_latency: automatic

inbound_services:
  - warmup
