---
version: 2.1

orbs:
  python: circleci/python@1.4

workflows:
  sample:
    jobs:
      - build-and-test:
          context:
            - docker
            - env
      - deploy-to-firebase:
          context:
            - docker
            - firebase
          requires:
            - build-and-test
      - deploy-to-gcp:
          context:
            - docker
          requires:
            - deploy-to-firebase

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mkdir -p test-results
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Coverage Test
          command: |
            coverage run ./manage.py test -v 2 --parallel
            coverage run ./manage.py check --deploy
            coverage report
            coverage html
            coverage xml
            coverage json
            COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
      - store_artifacts:
          path: test-results
      - run:
          name: Django Migration
          command: |
            python manage.py makemigrations
            python manage.py migrate

  deploy-to-firebase:
    docker:
      - image: andreysenov/firebase-tools
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Firebase Deployment
          command: |
            firebase deploy --only hosting --token $FIREBASE_TOKEN

  deploy-to-gcp:
    docker:
      - image: google/cloud-sdk
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS |
          gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project $GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
