version: 2.1

orbs:
  python: circleci/python@1.4

workflows:
  sample:
    jobs:
      - build-and-test:
          context:
            - docker
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ls
      - run: echo $DOCKERHUB_PASSWORD
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
          pypi-cache: true
      - run: echo Success!!
