---
version: 2.1

orbs:
  python: circleci/python@1.4

workflows:
  sample:
    jobs:
      - build-and-test:
          context:
            - docker
            - env
      - deploy-to-firebase:
          context:
            - docker
            - firebase
          requires:
            - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mkdir -p test-results
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
          pypi-cache: true
      - run:
          name: Run Test
          command: |
            python -Wa manage.py test --parallel
            coverage run --parallel-mode ./manage.py test
            COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
      - run:
          name: Django Migration
          command: |
            python manage.py makemigrations
            python manage.py migrate
      - run:
          name: Run Pytest
          command: |
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-results/
          destination: tr1

  deploy-to-firebase:
    docker:
      - image: andreysenov/firebase-tools
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Firebase Deployment
          command: |
            firebase deploy --only hosting --token $FIREBASE_TOKEN
  deploy:
    docker:
      - image: google/cloud-sdk
        auth:
          username: prynstag
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS |
          gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project $GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
